# Generated by Django 5.1.5 on 2025-01-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nome da Marca"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "model",
                    models.CharField(max_length=250, verbose_name="Modelo do Carro"),
                ),
                (
                    "factory_year",
                    models.PositiveIntegerField(verbose_name="Ano de Fabricação"),
                ),
                (
                    "model_year",
                    models.PositiveIntegerField(verbose_name="Ano do Modelo"),
                ),
                (
                    "plate",
                    models.CharField(max_length=10, verbose_name="Placa do Carro"),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("photo", models.ImageField(upload_to="cars/")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.brand"
                    ),
                ),
            ],
            options={
                "verbose_name": "Carro",
                "verbose_name_plural": "Carros",
            },
        ),
    ]
