# Generated by Django 5.1.5 on 2025-02-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_alter_car_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarInvetory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cars_count", models.IntegerField(verbose_name="Número de Carros")),
                (
                    "cars_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Valor total da Mercadoria",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Inventario de Carro",
                "verbose_name_plural": "Inventario de Carros",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor"
            ),
        ),
    ]
