# Generated by Django 5.1.5 on 2025-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_carinvetory_alter_brand_name_alter_car_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
