# Generated by Django 5.1.5 on 2025-02-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_car_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(null=True, upload_to="cars/"),
        ),
    ]
