# Generated by Django 5.1.5 on 2025-02-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0006_alter_car_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
